### ISSUE TITLE
index out of range in core_client.go

### ISSUE THREAD

**Issue by yb01** [futurewei-cloud/arktos#624]
**What happened**:
``` 
E0825 06:38:15.423190       6 reflector.go:181] object-"system"/"m9zamz-testns"/"default-token-496hl": Failed to list *v1.Secret: Get https://10.40.3.231:443/api/v1/tenants/system/namespaces/m9zamz-testns/secrets?fieldSelector=metadata.name%3D
default-token-496hl&limit=500&resourceVersion=0: net/http: TLS handshake timeout
I0825 06:38:15.904257       6 trace.go:81] Trace[69845232]: "Reflector object-\"system\"/\"hbiecu-testns\"/\"default-token-5f6h8\" ListAndWatch" (started: 2020-08-25 06:38:00.709589642 +0000 UTC m=+15308.643016890) (total time: 15.194645165s):
Trace[69845232]: [15.194635432s] [15.194635432s] Objects listed
I0825 06:38:16.422217       6 trace.go:81] Trace[1028905404]: "Reflector object-\"system\"/\"e2lf5j-testns\"/\"default-token-cscvd\" ListAndWatch" (started: 2020-08-25 06:38:00.980941305 +0000 UTC m=+15308.914368585) (total time: 15.441253196s
):
Trace[1028905404]: [15.441244106s] [15.441244106s] Objects listed
I0825 06:38:16.479164       6 update.go:141] ClientSetsWatcher: Started waiting for clientset update complete. current watcher 72. muxStartWaiting and muxUpdateServerMap are locked
E0825 06:38:16.479475       6 runtime.go:73] Observed a panic: "index out of range" (runtime error: index out of range)
goroutine 16153 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x36e9820, 0x727fc80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x36e9820, 0x727fc80)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1.(*CoreV1Client).RESTClient(0xc000271da0, 0xc00069d940, 0x4c)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1/core_client.go:284 +0x159
k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1.newSecretsWithMultiTenancy(0xc000271da0, 0xc000ec46d0, 0xd, 0xc000ec471a, 0x6, 0xc001dc4120)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1/secret.go:75 +0x2f
k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1.(*CoreV1Client).SecretsWithMultiTenancy(0xc000271da0, 0xc000ec46d0, 0xd, 0xc000ec471a, 0x6, 0x2, 0x2)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1/core_client.go:182 +0x53
k8s.io/kubernetes/pkg/kubelet/secret.NewWatchingSecretManager.func2(0xc000ec471a, 0x6, 0xc000ec46d0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/secret/secret_manager.go:143 +0x8f
k8s.io/kubernetes/pkg/kubelet/util/manager.(*objectCache).newReflector.func2(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00135d0e0, 0x21, 0x100, 0xc001d46c80, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/manager/watch_based_manager.go:97 +0xa4
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*ListWatch).Watch(0xc00124c3c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/listwatch.go:155 +0xaa
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0014d4d20, 0xc000cee120, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:399 +0x547
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:180 +0x2c1
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc001cdff78)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001cdff78, 0x3b9aca00, 0x0, 0x1, 0xc000cee120)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0014d4d20, 0xc000cee120)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:178 +0x16b
created by k8s.io/kubernetes/pkg/kubelet/util/manager.(*objectCache).newReflector
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/manager/watch_based_manager.go:109 +0x569
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range
goroutine 16153 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x36e9820, 0x727fc80)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
```
**What you expected to happen**:
should not be panic, and a client is returned

**How to reproduce it (as minimally and precisely as possible)**:
this is to track the panic found in perf run with a private branch : https://github.com/Sindica/arktos/tree/retry-on-failures.
Normally we don't file issue with private repo runs, but this one seems to be a legitimate bug after looking into it. still need to confirm with the code owner.

**Anything else we need to know?**:
the callback can be also found in issue #571 . # 4 in the list.
 

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yb01** [comment]
the panic comes from this code , return c.restClients[ran],  in the function below, in core_client.go file:
```
func (c *CoreV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}

	max := len(c.restClients)
	if max == 0 {
		return nil
	}
	if max == 1 {
		return c.restClients[0]
	}

	rand.Seed(time.Now().UnixNano())
	ran := rand.Intn(max)
	return c.restClients[ran]
}
```
Apparently the c.restClients slides were changed when this victim thread try to grab a client from it.

**Comment by yb01** [comment]
in constructing the clients slice from config:
```
// NewForConfig creates a new CoreV1Client for the given config.
func NewForConfig(c *rest.Config) (*CoreV1Client, error) {
	configs := rest.CopyConfigs(c)
	if err := setConfigDefaults(configs); err != nil {
		return nil, err
	}

	clients := make([]rest.Interface, len(configs.GetAllConfigs()))
	for i, config := range configs.GetAllConfigs() {
		client, err := rest.RESTClientFor(config)
		if err != nil {
			return nil, err
		}
		clients[i] = client
	}

	obj := &CoreV1Client{
		restClients: clients,
		configs:     configs,
	}

	obj.run()

	return obj, nil
}
```

the go routine to get the config from watch could be reset:
```
// run watch api server instance updates and recreate connections to new set of api servers
func (c *CoreV1Client) run() {
	go func(c *CoreV1Client) {
		member := c.configs.WatchUpdate()
		watcherForUpdateComplete := apiserverupdate.GetClientSetsWatcher()
		watcherForUpdateComplete.AddWatcher()

		for range member.Read {
			// create new client
			clients := make([]rest.Interface, len(c.configs.GetAllConfigs()))
			for i, config := range c.configs.GetAllConfigs() {
				client, err := rest.RESTClientFor(config)
				if err != nil {
					klog.Fatalf("Cannot create rest client for [%+v], err %v", config, err)
					return
				}
				clients[i] = client
			}
			c.restClients = clients
			watcherForUpdateComplete.NotifyDone()
		}
	}(c)
}
```

**Comment by yb01** [comment]
Update the more complete log indicating the issue -- where the c.restClients were reset to new slice.
