### ISSUE TITLE
Fatal error: concurrent map read and map write in kubelet/kuberuntime

### ISSUE THREAD

**Issue by sonyafenge** [futurewei-cloud/arktos#647]
**What happened**:
Run 10Knodes with 3 apiserver, 1 worklaod, 1 etcd, tried to create pods using deployments, get this fatal error:
 
```
I0817 21:04:15.601931       6 eviction_manager.go:230] eviction manager: synchronize housekeeping
E0817 21:04:15.601999       6 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get root cgroup stats: failed to get cgroup stats for "/": unexpected number of containers: 0
E0817 21:04:15.763973       6 docker_sandbox.go:703] ResolvConfPath is empty.
I0817 21:04:15.764013       6 plugins.go:381] Calling network plugin kubernetes.io/no-op to set up pod "ovo53knvefbeevgczsrjc0ekujygcksb-pods-549b6587bc-wcmr4_ovo53knvefbeevgczsrjc0ekujygcksb-ns_system"
I0817 21:04:15.764715       6 generic.go:154] GenericPLEG: 13b4509b-cb49-4b76-8378-6a39c0cf38e7/a5f4bdf89c12d5b6: non-existent -> running
I0817 21:04:15.764742       6 helpers.go:307] Retrieve runtime service for podID 13b4509b-cb49-4b76-8378-6a39c0cf38e7
fatal error: concurrent map read and map write
 
goroutine 722 [running]:
runtime.throw(0x3edfac7, 0x21)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc001b74fc0 sp=0xc001b74f90 pc=0x4308a2
runtime.mapaccess2_faststr(0x35e1ba0, 0xc00072da40, 0xc000eabe00, 0x24, 0xc001b75108, 0x1)
        /usr/local/go/src/runtime/map_faststr.go:116 +0x4a9 fp=0xc001b75030 sp=0xc001b74fc0 pc=0x415b39
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).GetRuntimeServiceByPodID(0xc0007828c0, 0xc000eabe00, 0x24, 0x15, 0xc0019d5ee8, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/helpers.go:309 +0xda fp=0xc001b751c8 sp=0xc001b75030 pc=0x19f5eda
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).getSandboxIDByPodUID(0xc0007828c0, 0xc000eabe00, 0x24, 0x0, 0xc001675200, 0x8, 0xc001704300, 0xc001705560, 0x40ea29)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go:313 +0xe4 fp=0xc001b75270 sp=0xc001b751c8 pc=0x1a18ee4
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).GetPodStatus(0xc0007828c0, 0xc000eabe00, 0x24, 0xc00054d340, 0x36, 0xc000eabe30, 0x23, 0xc000d54170, 0x6, 0x2f63074, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:1461 +0x66 fp=0xc001b75818 sp=0xc001b75270 pc=0x1a154d6
k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).updateCache(0xc0000f0d20, 0xc00013afc0, 0xc000eabe00, 0x24, 0xc000722178, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go:403 +0xe7 fp=0xc001b75930 sp=0xc001b75818 pc=0x2f62b97
k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc0000f0d20)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go:257 +0xbc0 fp=0xc001b75e90 sp=0xc001b75930 pc=0x2f619c0
k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist-fm()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go:189 +0x2a fp=0xc001b75ea8 sp=0xc001b75e90 pc=0x2f6368a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0001c1450)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54 fp=0xc001b75ee0 sp=0xc001b75ea8 pc=0x515d04
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0001c1450, 0x3b9aca00, 0x0, 0xc000181201, 0xc0000ce0c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8 fp=0xc001b75f90 sp=0xc001b75ee0 pc=0x514f98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0001c1450, 0x3b9aca00, 0xc0000ce0c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d fp=0xc001b75fc8 sp=0xc001b75f90 pc=0x514e8d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc001b75fd0 sp=0xc001b75fc8 pc=0x45fbd1
created by k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).Start
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go:132 +0x83
``` 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Logs are located under GCP workload-controller-manager project: 
sonya-uswest2:/home/sonyali/logs/perf-test/gce-5000/arktos/0817api3-wc1-etcd1-10000nodes/logs/
**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yb01** [comment]
Will take a look. we explicitly put the runtime-pod map in a RW mutex. will check if there is any code paths missed there.

**Comment by yb01** [comment]
this run that reported this issue is on 8/17. PR #598 ,  https://github.com/futurewei-cloud/arktos/pull/598, had already had a fix to it.

**Comment by yb01** [comment]
closed this issue after discussing with Sonya.

**Comment by yb01** [comment]
some info:
this perf run is on 8/17 and the stack indicates the code is before the PR #598 :
 ```
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).GetRuntimeServiceByPodID(0xc0007828c0, 0xc000eabe00, 0x24, 0x15, 0xc0019d5ee8, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/helpers.go:309 +0xda fp=0xc001b751c8 sp=0xc001b75030 pc=0x19f5eda
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).getSandboxIDByPodUID(0xc0007828c0, 0xc000eabe00, 0x24, 0x0, 0xc001675200, 0x8, 0xc001704300, 0xc001705560, 0x40ea29)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go:313 +0xe4 fp=0xc001b75270 sp=0xc001b751c8 pc=0x1a18ee4
```


    helper.go  line 309  is:
```
if runtimeService := m.getPodRuntimeService(string(podId)); runtimeService != nil {
```
